CREATE DATABASE QUANLYNHANVIEN_B6_2574802010821
GO 
USE QUANLYNHANVIEN_B6_2574802010821

CREATE TABLE NHANVIEN(HONV VARCHAR(15) NOT NULL,
						TENLOT VARCHAR(15) NOT NULL,
						   TENNV VARCHAR(15) NOT NULL,
							  MANV VARCHAR(9) NOT NULL,
								 NGSINH DATETIME NULL,
									DCHI VARCHAR(30) NULL,
									  PHAI VARCHAR(3) NOT NULL,
										 LUONG FLOAT NULL,
											MA_NQL VARCHAR(9) NULL,
												PHG INT NULL)

CREATE TABLE PHONGBAN(TENPHG VARCHAR(15) NOT NULL,
						MAPHG INT NOT NULL,
						   TRPHG VARCHAR(9) NOT NULL,
							  NG_NHANCHUC DATETIME NOT NULL)

CREATE TABLE DIADIEM_PHG(MAPHG INT NOT NULL,
							DIADIEM VARCHAR(15) NOT NULL)

CREATE TABLE PHANCONG(MA_NVIEN VARCHAR(9) NOT NULL,
						 SODA INT NOT NULL,
 							 THOIGIAN FLOAT NULL)

CREATE TABLE THANNHAN(MA_NVIEN VARCHAR(9) NOT NULL,
						 TENTN VARCHAR(15) NOT NULL,
							PHAI VARCHAR(3) NOT NULL,
								NGSINH DATETIME NULL,
									QUANHE VARCHAR(8) NOT NULL)

CREATE TABLE DEAN(TENDA VARCHAR(15) NOT NULL,
					 MADA INT NOT NULL,
						DDIEM_DA VARCHAR(15) NOT NULL,
							PHONG INT  NULL)

SELECT * FROM NHANVIEN WHERE PHG = 4

SELECT * FROM NHANVIEN WHERE LUONG >= 30000

SELECT * FROM NHANVIEN 
WHERE (LUONG > 25000 AND PHG = 4) 
   OR (LUONG > 30000 AND PHG = 5)

SELECT TENNV FROM NHANVIEN 
WHERE YEAR(NGSINH) < 1962 OR PHAI = 'Nam'

SELECT HONV, TENLOT, TENNV 
FROM NHANVIEN 
WHERE TENNV LIKE 'T%'

SELECT MADA, TENDA FROM DEAN WHERE PHONG = 5

SELECT N.MANV, N.TENNV, P.TENPHG 
FROM NHANVIEN N, PHONGBAN P 
WHERE N.PHG = P.MAPHG  









